CREATE TABLE bookmarks_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    rating DECIMAL NOT NULL,
    description TEXT
);

CREATE TYPE star_rating AS ENUM ('1','2','3','4','5');
